<?php
$z[0]=Array("arcurl","",84,99);
$z[1]=Array("title","",108,122);
$z[2]=Array("pubdate","",316,359);
$z[2][4]['function']="MyDate('m',@me)";
$z[3]=Array("pubdate","",373,416);
$z[3][4]['function']="MyDate('d',@me)";
$z[4]=Array("pubdate","",480,523);
$z[4][4]['function']="MyDate('Y',@me)";
$z[5]=Array("title","",724,738);
$z[6]=Array("description","",786,835);
$z[6][4]['function']="cn_substr(@me,60)";

?>