<?php
$z[0]=Array("field","",124,143);
$z[0][4]['name']="title";
$z[1]=Array("global","",144,170);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",211,233);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",273,324);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1024,1059);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1166,1185);
$z[5][4]['name']="title";
$z[6]=Array("field","",1324,1353);
$z[6][4]['name']="position";
$z[7]=Array("field","",1539,1558);
$z[7][4]['name']="title";
$z[8]=Array("field","",1972,1990);
$z[8][4]['name']="body";
$z[9]=Array("prenext","",2243,2268);
$z[9][4]['get']="pre";
$z[10]=Array("prenext","",2322,2348);
$z[10][4]['get']="next";
$z[11]=Array("type"," <a class=\"button border-main\" href=\"[field:typelink/]\">更多>></a>",2632,2734);
$z[11][4]['typeid']="3";
$z[12]=Array("arclist","\r\n      <div class=\"xl6 xs6 xm3 xb3 proitem\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" >\r\n        <h3>[field:title/]</h3>\r\n        </a> </div>\r\n      ",2791,3056);
$z[12][4]['typeid']="3";
$z[12][4]['row']="8";
$z[12][4]['titlelen']="50";
$z[12][4]['orderby']="pubdate";
$z[13]=Array("include","",3150,3187);
$z[13][4]['filename']="footer.htm";

?>