
<field:xm itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xm>

<field:yx itemname="标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:yx>


<field:nra itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:nra>

<field:sj itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sj>
