<?php
$z[0]=Array("flink","  [field:link /]  &nbsp;&nbsp;",116,206);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",478,499);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",593,614);
$z[2][4]['name']="cfg_dh";
$z[3]=Array("global"," </p>\r\n      <p>公司地址：{dede:global.cfg_dz",662,734);
$z[3][4]['name']="cfg_yx";
$z[4]=Array("sql"," \r\n        \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]...\r\n        \r\n        ",749,922);
$z[4][4]['sql']="Select content from dede_arctype where id=1";
$z[5]=Array("global","",1326,1350);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1435,1461);
$z[6][4]['name']="cfg_powerby";

?>