<?php
$z[0]=Array("field","",124,143);
$z[0][4]['name']="title";
$z[1]=Array("global","",144,170);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",211,240);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",280,338);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1037,1072);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1179,1198);
$z[5][4]['name']="title";
$z[6]=Array("field","",1337,1366);
$z[6][4]['name']="position";
$z[7]=Array("field","",1533,1562);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n      <div class=\"xl12 xs6 xm4 xb3 proitem\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" >\r\n        <h3>[field:title/]</h3>\r\n        </a> </div>\r\n      ",1617,1840);
$z[8][4]['pagesize']="8";
$z[9]=Array("pagelist","",1890,1956);
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[9][4]['listsize']="1";
$z[10]=Array("include","",2025,2062);
$z[10][4]['filename']="footer.htm";

?>